# Copyright (C) The Arvados Authors. All rights reserved.
#
# SPDX-License-Identifier: AGPL-3.0

# Note: The database configuration is not actually used.
development:
  adapter: nulldb
test:
  adapter: nulldb
production:
  adapter: nulldb
diagnostics:
  adapter: nulldb
performance:
  adapter: nulldb
